#!/bin/bash

echo "Running a qucik format!"

cargo fmt

cargo clippy -- -D warnings
if [ $? -eq 0 ]; then
	echo "LINTER PASSED! Everything looks good to-go"	
else
	EXEC_ERR="cargo clippy"

	echo ERR_MESSAGE

	exit 1
fi

exit 0
